/*
 * Metadata - jQuery plugin for parsing metadata from elements
 */
(function($){$.extend({metadata:{defaults:{type:'class',name:'metadata',cre:/({.*})/,single:'metadata'},setType:function(type,name){this.defaults.type=type;this.defaults.name=name;},get:function(elem,opts){var settings=$.extend({},this.defaults,opts);if(!settings.single.length)settings.single='metadata';var data=$.data(elem,settings.single);if(data)return data;data="{}";if(settings.type=="class"){var m=settings.cre.exec(elem.className);if(m)data=m[1];}else if(settings.type=="elem"){if(!elem.getElementsByTagName)return undefined;var e=elem.getElementsByTagName(settings.name);if(e.length)data=$.trim(e[0].innerHTML);}else if(elem.getAttribute!=undefined){var attr=elem.getAttribute(settings.name);if(attr)data=attr;}if(data.indexOf('{')<0)data="{"+data+"}";data=eval("("+data+")");$.data(elem,settings.single,data);return data;}}});$.fn.metadata=function(opts){return $.metadata.get(this[0],opts);};})(jQuery);
/*
 * jQuery cookie
 */
jQuery.cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{};if(value===null){value='';options.expires=-1;};var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else{date=options.expires;};expires='; expires='+date.toUTCString();};var path=options.path?'; path='+(options.path):'';var domain=options.domain?'; domain='+(options.domain):'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break;}}};return cookieValue;}};
/*
 * BASE64
 */
var BASE64={enKey:'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',deKey:new Array(-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1),encode:function(src){var str=new Array();var ch1,ch2,ch3;var pos=0;while(pos+3<=src.length){ch1=src.charCodeAt(pos++);ch2=src.charCodeAt(pos++);ch3=src.charCodeAt(pos++);str.push(this.enKey.charAt(ch1>>2),this.enKey.charAt(((ch1<<4)+(ch2>>4))&0x3f));str.push(this.enKey.charAt(((ch2<<2)+(ch3>>6))&0x3f),this.enKey.charAt(ch3&0x3f));};if(pos<src.length){ch1=src.charCodeAt(pos++);str.push(this.enKey.charAt(ch1>>2));if(pos<src.length){ch2=src.charCodeAt(pos);str.push(this.enKey.charAt(((ch1<<4)+(ch2>>4))&0x3f));str.push(this.enKey.charAt(ch2<<2&0x3f),'=');}else{str.push(this.enKey.charAt(ch1<<4&0x3f),'==');}};return str.join('');},decode:function(src){var str=new Array();var ch1,ch2,ch3,ch4;var pos=0;src=src.replace(/[^A-Za-z0-9\+\/]/g,'');while(pos+4<=src.length){ch1=this.deKey[src.charCodeAt(pos++)];ch2=this.deKey[src.charCodeAt(pos++)];ch3=this.deKey[src.charCodeAt(pos++)];ch4=this.deKey[src.charCodeAt(pos++)];str.push(String.fromCharCode((ch1<<2&0xff)+(ch2>>4),(ch2<<4&0xff)+(ch3>>2),(ch3<<6&0xff)+ch4));};if(pos+1<src.length){ch1=this.deKey[src.charCodeAt(pos++)];ch2=this.deKey[src.charCodeAt(pos++)];if(pos<src.length){ch3=this.deKey[src.charCodeAt(pos)];str.push(String.fromCharCode((ch1<<2&0xff)+(ch2>>4),(ch2<<4&0xff)+(ch3>>2)));}else{str.push(String.fromCharCode((ch1<<2&0xff)+(ch2>>4)));}};return str.join('');}};


$.metadata.setType("attr", "vld");